name: CI

on:
  push:
  pull_request:

jobs:
  android:
    runs-on: ubuntu-latest
    env:
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Configure SDK path for CI
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Install Android SDK packages
        shell: bash
        run: |
          # Avoid SIGPIPE failures under pipefail when auto-accepting licenses.
          set +o pipefail
          yes | sdkmanager --licenses > /dev/null
          sdkmanager "platforms;android-36" "platform-tools"

      - name: Build (Android)
        run: ./gradlew :composeApp:assembleDebug :composeApp:testDebugUnitTest --no-daemon --stacktrace
